## Machine Learning - Session 1 - NumPy

In [1]:
#Import the numpy library
import numpy as np

#### A. Defining a 1D numpy array

In [2]:
l = [12,34,24,45,7,18]

In [3]:
type(l)

list

In [4]:
x = np.array([12,34,24,45,7,18])
x

array([12, 34, 24, 45,  7, 18])

In [5]:
type(x)

numpy.ndarray

#### B. Creating Regular Sequence

In [ ]:
#Create a regular sequence of integers starting from 1 to 10. integers = [1,2,3,4,.......,10]

integers = np.arange(1, 11, 1)
integers

In [ ]:
#Create a regular sequence of integers starting from 10 to 1.

integers = np.arange(10, 0, -1)
integers

In [ ]:
#Create a regular sequence of even integers between 10 to 20

even = np.arange(10,21,2)
even

In [ ]:
#Create a regular sequence of the following type: [10.0,10.5,11.0,11.5, ... , 19.5, 20.0]

seq = np.arange(10,21,0.5)
seq


In [8]:
#Create a regular sequence of length 20 ranging from 0 to 5

np.linspace(start = 0, stop = 5, num = 20, endpoint = True)

array([0.        , 0.26315789, 0.52631579, 0.78947368, 1.05263158,
       1.31578947, 1.57894737, 1.84210526, 2.10526316, 2.36842105,
       2.63157895, 2.89473684, 3.15789474, 3.42105263, 3.68421053,
       3.94736842, 4.21052632, 4.47368421, 4.73684211, 5.        ])

In [ ]:
#Help for np.linspace

??np.linspace   #Shift + tab

In [ ]:
#Studying the arange function

help(np.arange)

#### C. Creating a Random Sequence

In [9]:
#Generate 20 random numbers between 1 and 100 (with replacements)
np.random.seed(0)
a = np.random.randint(1,100,20)
a

array([45, 48, 65, 68, 68, 10, 84, 22, 37, 88, 71, 89, 89, 13, 59, 66, 40,
       88, 47, 89])

In [ ]:
np.random.seed(0)
b=np.random.random(20)
b

In [ ]:
np.random.seed(0)
a+b

In [ ]:
#help(np.random.randint)

In [10]:
l = [12,34,24,45,7,18]

#Shuffle the vector x
x = np.array(l)
np.random.shuffle(x)
x

array([24, 45, 12,  7, 18, 34])

In [ ]:
x

In [11]:
np.random.choice(l,2)

array([ 7, 45])

In [12]:
np.random.choice(x,15,replace=True)

array([24,  7, 34, 24, 12,  7, 24, 45,  7, 34,  7,  7, 24, 45, 45])

In [15]:
np.random.choice(x,2,replace=False)

array([45, 18])

To find more on numpy random sampling Go To this link 
https://docs.scipy.org/doc/numpy-1.12.0/reference/routines.random.html 

#### D. Some basic numpy methods

In [16]:
[12,34,24.0,45,7,18]

[12, 34, 24.0, 45, 7, 18]

In [29]:
x = np.array([12,34,24,45,7.0,18])

In [18]:
#Size of the array
x.size

6

In [28]:
x = np.array([12,34,'24',45,7.0,18])
x

array(['12', '34', '24', '45', '7.0', '18'], dtype='<U11')

In [30]:
#data type
x.dtype

dtype('float64')

In [ ]:
#Type of the object
type(x)

In [31]:
#Type conversion
x.astype(int)

array([12, 34, 24, 45,  7, 18])

In [32]:
x.astype(str)

array(['12.0', '34.0', '24.0', '45.0', '7.0', '18.0'], dtype='<U32')

#### E. Some basic (1D) numpy operations

In [38]:
#Consider that we have two arrays

x = np.array([12,34,24,45,7,18])
y = np.array([3,6,8,55,1,10])

In [34]:
#Addition
x + y

array([15, 40, 32, 50,  8, 28])

In [35]:
y + 10

array([13, 16, 18, 15, 11, 20])

In [39]:
#Subtraction
x - y

array([  9,  28,  16, -10,   6,   8])

In [ ]:
#Multiplication by scalar
10*y

In [ ]:
y*(1/10)

In [ ]:
y/10

In [ ]:
#Element wise multiplication
x*y

In [37]:
#Using dot method
x.dot(y)

844

In [ ]:
np.sum(x*y)

In [ ]:
y.dot(x)

In [ ]:
np.dot(x,y)

In [ ]:
print(x)
print(y)

In [ ]:
#Taking the square root of each elements in an array
x**(1/2)

In [40]:
np.sqrt(x)

array([3.46410162, 5.83095189, 4.89897949, 6.70820393, 2.64575131,
       4.24264069])

In [41]:
np.exp(x)

array([1.62754791e+05, 5.83461743e+14, 2.64891221e+10, 3.49342711e+19,
       1.09663316e+03, 6.56599691e+07])

In [ ]:
np.log(x)

#### F. Some Useful Numpy Functions

In [ ]:
y = np.array([3,6,8,5,1,10])

In [ ]:
#Sum
np.sum(y)

In [ ]:
sum(y)

In [ ]:
#Mean
np.mean(y)

In [ ]:
#Standard Deviation
np.std(y)

In [ ]:
#Minimum
np.min(y)

In [ ]:
#Maximum
np.max(y)

In [42]:
#Percentiles
np.percentile(y,60)

8.0

In [43]:
np.percentile(y,[25, 62, 75])

array([3.75, 8.2 , 9.5 ])

In [44]:
#Sorting
np.sort(y)

array([ 1,  3,  6,  8, 10, 55])

In [46]:
#Sorting in descending order
-np.sort(-y)

array([55, 10,  8,  6,  3,  1])

#### G. Subsetting a 1D numpy array

In [47]:
x = np.array([12,34,24,45,7,18])
y = np.array([3,6,8,5,1,10])

In [48]:
#Subsetting and slicing is same as list
x[0]

12

In [49]:
x[1]

34

In [ ]:
y[3]

In [50]:
x[3:5]

array([45,  7])

In [51]:
x[[2,4]]

array([24,  7])

#### H. Conditional Subsetting

**The Comparison Operators**

      > is greater than
      < is less than
      == is equal to
      <= is less than or equal to
      >= is greater than or equal to

In [52]:
x = np.array([12,34,24,45,7,18])
y = np.array([3,6,8,5,1,10])

In [53]:
2 > 30

False

In [54]:
x > 20

array([False,  True,  True,  True, False, False])

In [55]:
y <= 5

array([ True, False, False,  True,  True, False])

In [56]:
sum(y <= 5)

3

In [ ]:
y == 1

**The Logical Operators**

    AND: &
    OR : |

In [57]:
(x>30) | (x<10)

array([False,  True, False,  True,  True, False])

In [ ]:
(x>10)

In [ ]:
(x<30)

In [ ]:
(x>10) | (x<30)

**Problems**

In [ ]:
#Consider the following two vectors

x = np.array([33,45,23,67,54,48])
y = np.array([108,151,164,119,135,122])

In [ ]:
np.logical_not(x < 35)

In [58]:
#a. Vaues of x that are less than 35

x[x < 35]

array([12, 34, 24,  7, 18])

In [ ]:
#no. of obs of y more than 150
y[y > 150].size

In [ ]:
#OR
sum(y > 150)

In [ ]:
#c. The number of observations in y that are between 120 and 165

sum((y >= 120) & (y <= 165))

In [ ]:
#d. The vaues in x that are less than 30 or greater than 50
x[((x < 30) | (x > 50))]

In [ ]:
#e. The values in x for which the values in y is less than or equal to 120
x[y <= 120]

In [ ]:
#f. The values in y for which the values in x is equal to 45
y[x == 45]

#### I. Defining a 2D numpy array

In [59]:
#Converting a 1D array into 2D array
x = np.array([33,45,23,67,54,48])

matrix = x.reshape(2,3)
matrix

array([[33, 45, 23],
       [67, 54, 48]])

In [60]:
matrix = x.reshape(3,2)
matrix

array([[33, 45],
       [23, 67],
       [54, 48]])

In [ ]:
#Create a 3x3 matrix containing elements from 1 to 9

np.arange(1,10).reshape(3,3)

In [61]:
#Joining two 1D arrays to form a matrix
x = np.array([33,45,23,67,54,48])
y = np.array([108,151,164,119,135,122])

matrix = np.array([x,y])
matrix

array([[ 33,  45,  23,  67,  54,  48],
       [108, 151, 164, 119, 135, 122]])

#### J. Some basic methods for 2D numpy array

In [62]:
matrix = np.array([ [38,33,47],
                    [29,48,35],
                    [21,34,47],
                    [38,44,21],
                    [28,26,43]])
matrix

array([[38, 33, 47],
       [29, 48, 35],
       [21, 34, 47],
       [38, 44, 21],
       [28, 26, 43]])

In [63]:
matrix.shape

(5, 3)

In [64]:
matrix.ndim

2

In [65]:
matrix.dtype

dtype('int32')

In [66]:
matrix.dtype.name

'int32'

In [67]:
matrix.size

15

In [68]:
#Size of the matrix in bytes
matrix.itemsize

4

#### K. Subsetting 2D numpy array

In [69]:
matrix = np.array([[38,33,47],
                    [29,48,35],
                    [21,34,47],
                    [38,44,21],
                    [28,26,43]])
matrix

array([[38, 33, 47],
       [29, 48, 35],
       [21, 34, 47],
       [38, 44, 21],
       [28, 26, 43]])

In [ ]:
#a) Print the first element of the matrix.
matrix[0,0]


In [ ]:
#b) Print the last element of the matrix.
matrix[matrix.shape[0]-1, matrix.shape[1]-1]


In [ ]:
matrix.shape

In [ ]:
#Or
matrix[-1,-1]

In [ ]:
matrix[0]

In [ ]:
#c) Print the values of the first row.

matrix[0,:]


In [ ]:
#d) Print the values of the fourth row.

matrix[3,:]


In [ ]:
#e) Print the values first column.

matrix[:,0]


In [ ]:
#f) Calculate the total of the third row.

np.sum(matrix[2,])


In [ ]:
matrix[2,]

In [ ]:
#g) Calculate the total of the fifth row.

np.sum(matrix[4,])


In [ ]:
#h) Calculate the total of the second column.

np.sum(matrix[:,1])


In [ ]:
#i) Calculate the average of the values of the first row.

np.mean(matrix[0,])


In [70]:
#j) Replace the first value of the matrix by 50.

matrix[0,0] = 50
matrix


array([[50, 33, 47],
       [29, 48, 35],
       [21, 34, 47],
       [38, 44, 21],
       [28, 26, 43]])

In [71]:
#k) Replace the last value of the matrix by 30.

matrix[-1, -1] = 30
matrix


array([[50, 33, 47],
       [29, 48, 35],
       [21, 34, 47],
       [38, 44, 21],
       [28, 26, 30]])

In [72]:
#l) Replace the second column of the matrix by the array (20,30,20,30,20)

matrix[:,1] = np.array([20,30,20,30,20])
matrix


array([[50, 20, 47],
       [29, 30, 35],
       [21, 20, 47],
       [38, 30, 21],
       [28, 20, 30]])

In [ ]:
np.mean(matrix[0, ])

In [73]:
#m) Replace the first row of the matrix by its average (calculated above).

matrix[0,:] = np.mean(matrix[0,:])

In [74]:
matrix

array([[39, 39, 39],
       [29, 30, 35],
       [21, 20, 47],
       [38, 30, 21],
       [28, 20, 30]])

In [75]:
#q) Calculate the sum of all the elements of the matrix

np.sum(matrix)

466

In [ ]:
#r) Calculate the sum of all the rows on the matrix

np.sum(matrix, axis=1)

In [ ]:
#s) Calculate the sum of all the colummns of the matrix

np.sum(matrix, axis=0)

#### L. Matrix Operations

In [76]:
#Defining a matrix 'm'
m = np.array([[2,3],[4,5]])
m

array([[2, 3],
       [4, 5]])

In [77]:
#Defining a matrix 'n'
n = np.array([[1,0],[3,6]])
n

array([[1, 0],
       [3, 6]])

In [ ]:
#Multiplication by scalar
2*n

In [ ]:
#Matrix addition
m + n

In [78]:
#Matrix Multilication
np.dot(m,n)

array([[11, 18],
       [19, 30]])

In [79]:
#Preferred - for Matrix Multilication
np.matmul(m,n)

array([[11, 18],
       [19, 30]])

In [80]:
#Preferred - for Matrix Multilication
m @ n

array([[11, 18],
       [19, 30]])

In [81]:
#Element-wise array multilication
np.multiply(m,n)

array([[ 2,  0],
       [12, 30]])

In [82]:
m*n

array([[ 2,  0],
       [12, 30]])

#### Copying data

In [88]:
p = np.array([2,5,8,6])

In [84]:
q = p #note that not new object is created

In [85]:
q

array([2, 5, 8, 6])

In [86]:
q[2] = 10
q

array([ 2,  5, 10,  6])

In [87]:
p

array([ 2,  5, 10,  6])

In [89]:
q = p.copy()

In [90]:
q[2] = 100
q

array([  2,   5, 100,   6])

In [91]:
p

array([2, 5, 8, 6])